config/routes.rb
Rails.application.routes.draw do
  resources :todos

  root 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.done = false
    @todo.save
    redirect_to @todo
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to @todo
  end

  private
  def todo_params
    params.require(:todo).permit(:title, :description, :done)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
<%= form_for :todo, url: todo_path(@todo), method: :patch do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  <%= f.label :done %><br>
  <%= f.check_box :done %><br>
  <%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1>Todos</h1>
<table border="1">
  <% @todos.each do |todo| %>
    <tr>
      <td>
        <%= todo.title %>
      </td>
      <td>
        <%= link_to 'show', todo_path(todo)%>
      </td>
      <td>
        <%= link_to 'edit', edit_todo_path(todo)%>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'new todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>Create new Todo</h1>

<%= form_for :todo, url: todos_path  do |f| %>
  <%= f.label :title %><br>
   <%= f.text_field :title %><br>
    <%= f.label :description %><br>
     <%= f.text_field :description %><br>
       <%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1>Ich bin ein Todo</h1>
<h3> <%= @todo.title %> </h3>
<br>
<%= @todo.description %>
<br>
<%= form_for :todo, url: todo_path(@todo), method: :patch do |f| %>
  <%= f.label :done %><br>
  <%= f.check_box :done %><br>
  <%= f.submit %>
<% end %>
<%= link_to 'all todos', todos_path %>

app/views/welcome/index.html.erb
<h1>Hallo Welt</h1>